#!/bin/bash
# Run with:
# ./ansible -K --limit production
if [[ $@ != *"--limit"*  ]]
then
    echo 'Please limit provisioning to production or staging with "--limit production/staging"'
else
    if [[ $@ =~ "production"  ]]
    then
        read -r -p "Going to provision a production box. Are you sure? [y/N] " response
        if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]
        then
            /usr/bin/env ansible-playbook ansible/provision.yml -i ansible/hosts --private-key=ansible/key.pem "$@"
        else
           echo 'Aborting production deploy because you told me to.'
        fi
    else
        /usr/bin/env ansible-playbook ansible/provision.yml -i ansible/hosts --private-key=ansible/key.pem "$@"
    fi
fi